### ISSUE TITLE
the docker http port was wrong

### ISSUE THREAD

**Issue by conanx2008** [portainer/portainer-docs#254]
when i look at the installtion docs, i found  the command was wrong, it wil be port 9000, but the docs show me it's 8000.

[https://github.com/portainer/portainer-docs/blob/2.16/start/install/server/docker/linux.md](https://github.com/portainer/portainer-docs/blob/2.16/start/install/server/docker/linux.md)

`docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ee:latest`

**Comment by jamescarppe** [comment]
If you read further back in that page you'll find the following:

> By default, Portainer Server will expose the UI over port 9443 and expose a TCP tunnel server over port 8000. The latter is optional and is only required if you plan to use the Edge compute features with Edge agents.

As indicated there, port `8000` is for the Edge compute functionality for Edge agents. We moved to using `9443` as the default UI port in order to push users towards using HTTPS rather than HTTP. If you still want to use port `9000`, you'll also find on that same page just after the command:

> If you require HTTP port 9000 open for legacy reasons, add the following to your docker run command:
-p 9000:9000

**Comment by conanx2008** [comment]
oh, my god . i make a mistake sorrysorry
