### ISSUE TITLE
On page https://docs.portainer.io/start/upgrade/docker - should the http ports exposed in the docker run commands be 9000 rather than 8000?

### ISSUE THREAD

**Issue by swinster** [portainer/portainer-docs#256]
Hi,

I'm just looking to upgrade a p[roptainer container, which currently uses HTTP exposed and mapped to port 9000. In the intro on that page, you say that HTTPS is now the default, but if you want to continue using HTTP, then add `-p 9000:9000` to the `docker run` command (or `docker-compose.yaml`). However, in the published `docker run` commands, you reference port `8000`:

BE:
```
docker run -d -p 8000:8000 -p 9443:9443 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ee:latest
```
CE
```
docker run -d -p 8000:8000 -p 9443:9443 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
```

Is this correct?

**Comment by jamescarppe** [comment]
From our[ installation instructions](https://docs.portainer.io/start/install/server/docker/linux):

> By default, Portainer Server will expose the UI over port 9443 and expose a TCP tunnel server over port 8000. The latter is optional and is only required if you plan to use the Edge compute features with Edge agents.

If you haven't used port `8000` before in your deployments and don't intend to use Edge agents, you can safely omit this port. Since port `8000` is exposed in our default installation commands, we include it in the upgrade instructions as well.
