### ISSUE TITLE
Limited Control vs Full Control

### ISSUE THREAD

**Issue by Sarke** [portainer/portainer-docs#75]
Stacks are marked as Portainer having Limited or Full control.  For example:

> This stack was created outside of Portainer. Control over this stack is limited.

However, I don't believe it is ever explained anywhere in the documentation what exactly the difference is, nor **how** is is limited.

What additional benefits do we get with "Full Control"?

**Comment by maltokyo** [comment]
Would also like to know this.  And how to migrate them into portainer if thats better.

**Comment by itsconquest** [comment]
Hi there, there is a bit of info on this in the [FAQ](https://portainer.readthedocs.io/en/stable/faq.html#why-are-my-stacks-marked-as-limited-in-portainer) already, however I have pushed an update to the FAQ to make this a little clearer. My update (copied below) will be live on the documentation site with the next release of Portainer (v1.23.2).

Why are my stacks showing as Limited in Portainer?
=================================================

A **Limited** stack as the name implies has limited functionality. This includes browsing through to related services from the Stack Details view, or deleting the stack.
A stack could show as Limited in Portainer, either because the stack was deployed outside of Portainer (Portainer doesn't have a copy of the Stack file) or because
the Portainer database has been lost (the volume it is on isn't persisted/highly available).

A **Total control** stack in Portainer brings you added functionality such as editing and updating a stack, duplicating the stack or migrating the stack. 
If you wish to have a Total control stack , you will need to deploy it within Portainer so that the file is kept in the database & ensure that the database is persisted and/or highly available.

**Comment by itsconquest** [comment]
We do not currently have functionality to turn a **Limited** stack (already deployed via the CLI) into a **Total Control** stack within Portainer. You will have to re-deploy the stack in Portainer using the stack file to have it show as a **Total Control** stack.

**Comment by itsconquest** [comment]
I will close this as I believe it is now resolved

**Comment by Crimzin69** [comment]
> We do not currently have functionality to turn a **Limited** stack (already deployed via the CLI) into a **Total Control** stack within Portainer. You will have to re-deploy the stack in Portainer using the stack file to have it show as a **Total Control** stack.

Has this been implemented yet? I am running EE version 2.10.0
![image](https://user-images.githubusercontent.com/19303352/150498292-c692e5eb-601d-4c0c-8a0e-902df258a140.png)

**Comment by NonaSuomy** [comment]
Chicken and egg issue, I trashed all my containers created by cli and then redeployed them through the stack option to get them to show as total but I'm not sure how to get portainer itself to show itself as total instead of limited... any idea?

**Comment by jamescarppe** [comment]
> Chicken and egg issue, I trashed all my containers created by cli and then redeployed them through the stack option to get them to show as total but I'm not sure how to get portainer itself to show itself as total instead of limited... any idea?

The "limited" state displays when a stack is deployed outside of Portainer. Since Portainer can't be deployed from within itself (as it won't exist to do so), the Portainer container will always display this state. As you shouldn't need to work on the Portainer container directly at any point, this shouldn't be an issue.

**Comment by Oekel** [comment]
Sorry, that is crappy. I created 4 stacks (all direct inside portainer) and after a while (some hours) I get this limited access and loosing the editor for the stack/compose.

Please tell me what courses this failure of data. ThanX
