### ISSUE TITLE
accessing traefik with portainer install

### ISSUE THREAD

**Issue by lester-s** [portainer/portainer-docs#97]
Hello,

I just installed portainer  with traefik following this tutorial:
https://documentation.portainer.io/v2.0/ad/traefik/rp-traefik/
Everything went fine. Great tutorial.
My problem is that i cannot find how to get acces to the traefik UI. I tried adding a port 8080 on the traefik port list.

Can you help me ?

**Comment by xe-nvdk** [comment]
Hi. It is not a problem. It is expected because the dashboard is not defined in that recipe. Take a look at this recipe to add the missing commands and create the dashboard's entry point. 

https://github.com/xe-nvdk/awesome-docker/tree/main/traefik-nextcloud-psql

For more support for Traefik, I recommend you drop your query in github.com/traefik.

**Comment by lester-s** [comment]
Hey ! 

Thank you very much for your help i al gonna try this. And you are right that could have been more a traefik gitlab question

Have a nice day
